### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by snorpey**
Make the box headlines sound a little bit nicer, while removing superflous dashes. Maybe @Toromino can provide some feedback on this change.

### CODE REVIEW

**Comment by ramsonline** [comment]
how about simply not using the "Coming Soon!": "Erscheint bald!" translation ?
I think that "coming soon" is also used in movie trailers and everyone in germany knows what it means.

just my thought what do you think of it ?

**Comment by snorpey** [comment]
@ramsonline sounds good!

What do you thing about replacing `Die Möglichkeit Bilder zu teilen` with `Eine Foto-Community`

and `für jeden` with `für alle`?

**Comment by ramsonline** [comment]
Yeah id replace it with "Eine unabhängige föderierende Foto-Community für alle" or something comparable. <-- thats the **main difference** to other Photo communities.

Moreover id do some small changes : 
"Funktionsreiches Dashboard und Tools" to "umfangreiches Benutzerinterface" 
(i actually do no know what is meant with "Tools". Are there any ?) 

"Hashtags, Discover, DMs": "Hashtags, Funktion zum Entdecken, Direktnachrichten",
"Hashtag und Messaging Support" - Its hard to express discovery functions in german without making it sound weird...

**Comment by snorpey** [comment]
I think "Powerful dashboard/tools" is probably referring to moderation tools for admins.

How about:
* `"Powerful dashboard/tools": "Umfangreiche Moderationswerkzeuge"`
* `"APIs that won't change": "Stabile APIs"`
* `"Hashtags, Discover, DMs": "Hashtag und Messaging Support"`
* `"A Photo Sharing Experience": "Eine unabhängige, föderierende Foto-Community"`
* `"for everyone": "für alle"`

**Comment by dansup** [comment]
@snorpey @ramsonline Thanks for your contributions!

**Pull request merged**
