### PR TITLE
Fixing capitals and images/photos

### PR DESCRIPTION
**Pull request by moshpirit**
Read issue #41 and its comments for more information

### CODE REVIEW

**Comment by dansup** [comment]
Hi, @allvoxman contributed the original es translations in #5, I would like to get some feedback from them about this.

**Comment by moshpirit** [comment]
Sure!

**Comment by allvoxman** [comment]
I disagree with the capitals argument. You're totally allowed to use capitals when you're dealing with a promotional text like this (just like in English).

**Comment by moshpirit** [comment]
No, that's grammatically incorrect: http://lema.rae.es/dpd/srv/search?id=BapzSnotjD6n0vZiTp

Also not used at all in this kind of context (consequence of being grammatically wrong) and it feels weird to read.

Also in this specific situation it fits better with just 1 capital letter and the rest in lowercase.

cc/ @victorhck

**Comment by allvoxman** [comment]
See point 4.32 of your link. Also, read pages 515-516 from the last issue of 'Ortografía' by the RAE (same use case). There you'll find the exceptions for the use of capitals in publicity. That's my understanding of this.

**Comment by moshpirit** [comment]
Oops! You're right, sorry. My bad. Knowing this makes me feel less annoyed about capitals haha.

Anyway it still seems weird to me, I think lowercase fits better. Maybe because "para todo el mundo" is already in lowercase, so it would be more coherent. What do you think?

**Comment by allvoxman** [comment]
No prob! Yes, absolutely. My translation was a quickie. I do agree that it could be enhanced visually, meaning that contributors should take some minor "editor decisions" here since this is such a trivial issue, if @dansup allows us... Shall we, Daniel?

**Pull request merged**
